services:
  postgres:
    image: postgres:16
    container_name: ec-cash-postgres
    environment:
      POSTGRES_DB: ec_cash_app
      POSTGRES_USER: ec_cash
      POSTGRES_PASSWORD: ec_cash
    ports:
      - "5432:5432"
    volumes:
      - ec_cash_postgres:/var/lib/postgresql/data

volumes:
  ec_cash_postgres:

