spring:
  application:
    name: ec-cash-app
  datasource:
    url: jdbc:postgresql://localhost:5432/ec_cash_app
    username: ec_cash
    password: ec_cash
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  thymeleaf:
    cache: false

server:
  port: 8080

app:
  admin:
    username: admin
    password: admin123

